INSERT INTO mytable(Symptom,Nutrient) VALUES
 ('Eye problems (incl. sensitive,itching,burning,bloodshot,blurred,cataracts,opaque cornea,near sightedness,glaucoma)','A')
,('osteomalacia','A')
,('osteopenia','A')
,('bone pain','A')
,('poor bone growth','A')
,('dry or rough skin','A')
,('spasms','A')
,('cramps','A')
,('low resistance to infections','A')
,('excessive mucus','A')
,('bronchitis','A')
,('Asthma','A')
,('psoriasis','A')
,('acne','A')
,('dry hair','A')
,('longitudinal ridges and brittle peeling nails','A')
,('poor smell and taste','A')
,('Poor circulation with cold hands and feet','B1')
,('edema (fluid retention)','B1')
,('furrowed tongue','B1')
,('underactive thyroid','B1')
,('Fatigue','B1')
,('depression','B1')
,('insomnia','B1')
,('anxiety','B1')
,('acidosis','B1')
,('over-sensitivity to pain and noise','B1')
,('nausea','B1')
,('poor memory','B1')
,('Apathy (Lack of interest)','B1')
,('debility','B1')
,('weight loss','B1')
,('muscles weak and painful','B1')
,('burning feet','B1')
,('gastrointestinal disturbances','B1')
,('rapid pulse and breathlessness on exertion','B1')
,('slow pulse at rest','B1')
,('enlarged and weak heart','B1')
,('mental illness','B1')
,('diabetes','B1')
,('hypoglycaemia','B1')
,('allergies','B1')
,('Eye problems (incl. sensitive,itching,burning,bloodshot,blurred,cataracts,opaque cornea,near sightedness,glaucoma)','B2')
,('skin oily and itching','B2')
,('eczema (especially around nose,forehead,ears,genetalia)','B2')
,('red patches on face (rosacea)','B2')
,('acne','B2')
,('bedsores','B2')
,('hair dull and oily','B2')
,('dandruff','B2')
,('split nails','B2')
,('sore tongue','B2')
,('cracks on lips and corners of mouth','B2')
,('allergies','B2')
,('reduced neurotransmitters','B2')
,('anaemia','B2')
,('arthritis and diabetes','B2')
,('dermatitis','B2')
,('dizziness','B2')
,('hair loss','B2')
,('insomnia','B2')
,('light sensitivity','B2')
,('poor digestion','B2')
,('Retarded growth','B2')
,('slow mental responses','B2')
,('Adrenal Weakness','B2')
,('Burning feet','B2')
,('coated tongue','B3')
,('sores in the mouth','B3')
,('irritability','B3')
,('nervousness','B3')
,('skin lesions','B3')
,('diarrhoea','B3')
,('forgetfulness','B3')
,('insomnia','B3')
,('chronic headaches','B3')
,('digestive disorders','B3')
,('anaemia','B3')
,('Weakness of the nerves','B3')
,('mental disturbances','B3')
,('depression','B3')
,('mental dullness and disorientation','B3')
,('rough skin','B3')
,('sore red eyes','B3')
,('cracked skin on areas exposed to the sun','B3')
,('inflammation of the mouth and tongue','B3')
,('abdominal pain and swelling','B3')
,('diarrhoea','B3')
,('anxiety','B3')
,('schizophrenia','B3')
,('hyperthyroidism','B3')
,('crying spells','B3')
,('suspicion','B3')
,('loss of humour','B3')
,('dermatitis','B3')
,('dementia','B3')
,('Fatigue','B5')
,('headache','B5')
,('insomnia','B5')
,('depression','B5');
INSERT INTO mytable(Symptom,Nutrient) VALUES
 ('nausea','B5')
,('abdominal cramps','B5')
,('occasional vomiting','B5')
,('burning feet','B5')
,('muscle cramps','B5')
,('impaired co-ordination','B5')
,('greying hair','B5')
,('arthritis','B5')
,('Asthma','B5')
,('Adrenal weakness','B5')
,('irritability','B5')
,('low blood sugar levels','B5')
,('allergies','B5')
,('Weakness','B6')
,('depression','B6')
,('mental confusion','B6')
,('irritability and nervousness','B6')
,('mood swings','B6')
,('insomnia','B6')
,('poor co-ordination in walking','B6')
,('hyperactivity','B6')
,('poor immune function','B6')
,('declining blood lymphocytes','B6')
,('anaemia','B6')
,('skin lesions','B6')
,('dry skin','B6')
,('oily skin','B6')
,('rashes','B6')
,('scaly skin around scalp, eyebrows and behind ear','B6')
,('PMS/PMT','B6')
,('morning sickness','B6')
,('fluid retention','B6')
,('nervous system disorders','B6')
,('muscle spasms','B6')
,('sleeplessness','B6')
,('inability to recall dreams','B6')
,('Muscle weakness','B6')
,('autism','B6')
,('lack of gastric acid','B6')
,('nail ridges along length','B6')
,('inability to tan in sunlight','B6')
,('allergies','B6')
,('poor appetite','B6')
,('hormone imbalances','B6')
,('Digestive problems','B7 Biotin')
,('nervous complaints','B7 Biotin')
,('anaemia','B7 Biotin')
,('Fatigue','B7 Biotin')
,('depression','B7 Biotin')
,('thin splitting nails','B7 Biotin')
,('poor hair','B7 Biotin')
,('poor appetite','B7 Biotin')
,('seborrhoeic dermatitis','B7 Biotin')
,('dry skin','B7 Biotin')
,('hair loss','B7 Biotin')
,('immune dysfunction','B7 Biotin')
,('Anaemia','B9 Folic Acid')
,('cracks in the corners of the mouth','B9 Folic Acid')
,('red, sore tongue','B9 Folic Acid')
,('greying hair','B9 Folic Acid')
,('greyish brown skin pigmentation','B9 Folic Acid')
,('irritability','B9 Folic Acid')
,('depression','B9 Folic Acid')
,('Fatigue','B9 Folic Acid')
,('forgetfulness','B9 Folic Acid')
,('lack of concentration','B9 Folic Acid')
,('mental confusion','B9 Folic Acid')
,('psychosis','B9 Folic Acid')
,('insomnia','B9 Folic Acid')
,('anxiety','B9 Folic Acid')
,('dizziness','B9 Folic Acid')
,('depressed reflexes','B9 Folic Acid')
,('headaches','B9 Folic Acid')
,('Muscle weakness','B9 Folic Acid')
,('numbness in legs','B9 Folic Acid')
,('difficulty in walking','B9 Folic Acid')
,('cramps','B9 Folic Acid')
,('digestive problems','B9 Folic Acid')
,('constipation','B9 Folic Acid')
,('diarrhoea','B9 Folic Acid')
,('sexual and circulation problems','B9 Folic Acid')
,('hypoglycaemia','B9 Folic Acid')
,('birth defects','B9 Folic Acid')
,('gout','B9 Folic Acid')
,('cardiovascular disease','B9 Folic Acid')
,('diabetes','B9 Folic Acid')
,('poor appetite','B9 Folic Acid')
,('Pernicious anaemia','B12')
,('Fatigue','B12')
,('Weakness','B12')
,('poor circulation','B12')
,('numbness and stiffness','B12')
,('red, sore tongue','B12')
,('emotional disturbances','B12')
,('mental illness','B12')
,('liver and nervous system diseases','B12')
,('nerve inflammations','B12')
,('Weakness','B12')
,('depression','B12')
,('allergies','B12');
INSERT INTO mytable(Symptom,Nutrient) VALUES
 ('pale skin','B12')
,('mouth ulcers','B12')
,('Apathy (Lack of interest)','B12')
,('shortness of breath','B12')
,('palpitations','B12')
,('mood changes','B12')
,('poor concentration','B12')
,('sexual problems/impotence/sterility','B12')
,('nervousness','B12')
,('poor memory','B12')
,('elevated homocysteine levels','B12')
,('Lassitude','C')
,('Weakness','C')
,('irritability','C')
,('depression','C')
,('muscle and joint pains','C')
,('scurvy','C')
,('easy bleeding of gums, skin and nose','C')
,('capillary weakness','C')
,('Fatigue','C')
,('poor wound healing','C')
,('acute and chronic infections','C')
,('liver and kidney problems','C')
,('ageing skin','C')
,('thrombosis','C')
,('Eye problems (incl. sensitive,itching,burning,bloodshot,blurred,cataracts,opaque cornea,near sightedness,glaucoma)','C')
,('arthritis','C')
,('diabetes','C')
,('anaemia','C')
,('bedsores','C')
,('stone formation','C')
,('backache','C')
,('anxiety','C')
,('Asthma','C')
,('hayfever','C')
,('headaches','C')
,('rashes','C')
,('easy bruising','C')
,('Rickets','D')
,('deformed and porous bones','D')
,('teeth and gum problems','D')
,('Muscle weakness','D')
,('cramps','D')
,('tetany','D')
,('nervous instability','D')
,('underactive thyroid','D')
,('depression','D')
,('overweight','D')
,('Eye problems (incl. sensitive,itching,burning,bloodshot,blurred,cataracts,opaque cornea,near sightedness,glaucoma)','D')
,('calcium deficiency','D')
,('Fatigue','D')
,('arthritis','D')
,('stiffness','D')
,('backache','D')
,('Lack of vitality','E')
,('lethargy','E')
,('Apathy (Lack of interest)','E')
,('lack of concentration','E')
,('irritability','E')
,('decreased sexual interest','E')
,('Muscle weakness','E')
,('Fatigue','E')
,('premature ageing','E')
,('circulatory disorders','E')
,('varicose veins','E')
,('thrombophlebitis','E')
,('claudication','E')
,('kidney inflammation','E')
,('degeneration of the sex glands','E')
,('poor wound healing','E')
,('cramps','E')
,('Fragile or deformed bones','Calcium')
,('muscle cramps','Calcium')
,('irritability','Calcium')
,('headaches','Calcium')
,('depression','Calcium')
,('menstrual problems','Calcium')
,('excessive and painful menstruation','Calcium')
,('poor circulation','Calcium')
,('tender breasts','Calcium')
,('undue sensitivity to pain','Calcium')
,('insomnia','Calcium')
,('allergies','Calcium')
,('inflammations','Calcium')
,('low blood pressure','Calcium')
,('varicose veins','Calcium')
,('piles','Calcium')
,('distended veins and abdomen','Calcium')
,('swellings','Calcium')
,('poor wound healing','Calcium')
,('pyorrhoea','Calcium')
,('gingivitis','Calcium')
,('Eye problems (incl. sensitive,itching,burning,bloodshot,blurred,cataracts,opaque cornea,near sightedness,glaucoma)','Calcium')
,('muscle twitching','Calcium')
,('Weakness','Calcium')
,('Apathy (Lack of interest)','Magnesium')
,('confusion','Magnesium')
,('depression','Magnesium')
,('disorientation','Magnesium')
,('hallucinations','Magnesium');
INSERT INTO mytable(Symptom,Nutrient) VALUES
 ('irritability','Magnesium')
,('paranoia','Magnesium')
,('poor memory','Magnesium')
,('angina','Magnesium')
,('arteriosclerosis','Magnesium')
,('high blood pressure','Magnesium')
,('sweating','Magnesium')
,('rapid pulse','Magnesium')
,('muscle cramps','Magnesium')
,('epilepsy','Magnesium')
,('muscle twitching','Magnesium')
,('numbness','Magnesium')
,('rapid eye movements','Magnesium')
,('tingling','Magnesium')
,('tremors','Magnesium')
,('stiffness','Magnesium')
,('kidney and gall bladder stones','Magnesium')
,('prostate problems','Magnesium')
,('overactive thyroid','Magnesium')
,('Colic ( frequent crying infants)','Magnesium')
,('premenstrual tension','Magnesium')
,('mitral valve prolapse','Magnesium')
,('attention deficit disorder','Magnesium')
,('fibromyalgia','Magnesium')
,('Asthma','Magnesium')
,('allergies','Magnesium')
,('Fatigue','Iron')
,('rapid pulse','Iron')
,('palpitations','Iron')
,('rapid breathing on exertion','Iron')
,('sore tongue','Iron')
,('breathlessness','Iron')
,('feeling very tired','Iron')
,('dizziness','Iron')
,('feeling cold even when it''s warm','Iron')
,('rapid weak pulse','Iron')
,('palpitations','Iron')
,('headache','Iron')
,('brittle and spoon shaped nails','Iron')
,('tinnitus (ringing in the ears)','Iron')
,('sores at the corners of the mouth','Iron')
,('taste bud atrophy (hence altered sense of taste)','Iron')
,('Goiter','Iodine')
,('Cretinism (severe retarded physical/mental growth, hypothyroidism)','Iodine')
,('Fatigue','Iodine')
,('overweight','Iodine')
,('mental retardation','Iodine')
,('debility (being weak/feeble)','Iodine')
,('cancer','Iodine')
,('blood sugar problems','Iodine')
,('diabetes','Iodine')
,('poor hair skin and nails','Iodine')
,('rapid pulse','Iodine')
,('cold body','Iodine')
,('constipation','Iodine')
,('Weakness','Iodine')
,('excessive menstruation','Iodine')
,('nervousness','Iodine')
,('irritability','Iodine')
,('low resistance to colds and infections','Iodine')
,('low energy levels','Iodine')
,('Muscle weakness','Manganese')
,('poor memory','Manganese')
,('dark red skin spots','Manganese')
,('diabetes','Manganese')
,('hypoglycaemia','Manganese')
,('atherosclerosis','Manganese')
,('schizophrenia','Manganese')
,('bone deformities','Manganese')
,('mucus problems','Manganese')
,('sexual problems/impotence/sterility','Manganese')
,('poor muscle co -ordination','Manganese')
,('inner ear problems','Manganese')
,('dizziness','Manganese')
,('bone calcium loss','Manganese')
,('dermatitis','Manganese')
,('abnormal blood sugar metabolism','Manganese')
,('low chloesterol levels','Manganese')
,('nerve and muscle disorders.','Manganese')
,('Anxiety','Potassium')
,('nervousness','Potassium')
,('Fatigue','Potassium')
,('diabetes','Potassium')
,('hypoglycaemia','Potassium')
,('heart strain','Potassium')
,('high blood pressure','Potassium')
,('liver problems','Potassium')
,('lower back pain','Potassium')
,('Muscle weakness','Potassium')
,('multiple sclerosis','Potassium')
,('overweight','Potassium')
,('stroke','Potassium')
,('high blood pressure','Potassium')
,('congestive heart failure','Potassium')
,('cardiac arrhythmias','Potassium')
,('palpitations','Potassium')
,('Muscle weakness','Potassium')
,('hyperthyroid','Potassium')
,('blood sugar disorders','Potassium')
,('Apathy (Lack of interest)','Potassium');
INSERT INTO mytable(Symptom,Nutrient) VALUES
 ('depression','Potassium')
,('erectile dysfunction','Potassium')
,('Fatigue','Potassium')
,('Weakness','Potassium')
,('Low blood fluid volume','Sodium')
,('thick blood','Sodium')
,('collapsed veins','Sodium')
,('low/high blood pressure','Sodium')
,('rapid pulse','Sodium')
,('Apathy (Lack of interest)','Sodium')
,('poor appetite','Sodium')
,('dehydration','Sodium')
,('dizziness','Sodium')
,('muscle cramps','Sodium')
,('headache','Sodium')
,('nausea','Sodium')
,('acidosis','Sodium')
,('muscle twitches','Sodium')
,('Muscle weakness','Sodium')
,('lack of thirst','Sodium')
,('excess brain water retention','Sodium')
,('High blood pressure (Excess Sodium!)','Sodium')
,('water retention (Excess Sodium!)','Sodium')
,('nephritis (Excess Sodium!)','Sodium')
,('eye bags (Excess Sodium!)','Sodium')
,('low calcium levels (Excess Sodium!)','Sodium')
,('low magnesium levels (Excess Sodium!)','Sodium')
,('potassium disturbances (Excess Sodium!)','Sodium')
,('Scar tissue','Sulphur')
,('wrinkles','Sulphur')
,('damaged skin','Sulphur')
,('lung dysfunction','Sulphur')
,('diabetes','Sulphur')
,('sore joints and muscles','Sulphur')
,('tendency to develop gastric and duodenal ulcers','Sulphur')
,('migraine headaches','Sulphur')
,('allergic reactions','Sulphur')
,('candida albacans','Sulphur')
,('infections','Sulphur')
,('Fatigue','Sulphur')
,('high cholesterol','Sulphur')
,('diverticulosis','Sulphur')
,('Shortness of breath (feelings of lack of oxygen)(Excess Sulphur!)','Sulphur')
,('headaches(Excess Sulphur!)','Sulphur')
,('thirst(Excess Sulphur!)','Sulphur')
,('anxiety (especially before sleeping)(Excess Sulphur!)','Sulphur')
,('Acne','Zinc')
,('boils','Zinc')
,('poor wound healing','Zinc')
,('psoriasis','Zinc')
,('stretch marks','Zinc')
,('brittle coarse hair','Zinc')
,('dandruff','Zinc')
,('white spots on nails','Zinc')
,('night blindness','Zinc')
,('lost sense of taste and smell','Zinc')
,('canker sores','Zinc')
,('sexual problems/impotence/sterility','Zinc')
,('enlarged prostate','Zinc')
,('irregular menstruation','Zinc')
,('poor growth','Zinc')
,('body and breath odour','Zinc')
,('nausea','Zinc')
,('cold extremities','Zinc')
,('diabetes','Zinc')
,('tendency to develop gastric and duodenal ulcers','Zinc')
,('inflammation of the intestines','Zinc')
,('joint pains','Zinc')
,('hyperactivity','Zinc')
,('learning disorder','Zinc')
,('schizophrenia','Zinc')
,('poor appetite','Zinc')
,('allergies','Zinc')
,('poor circulation','Zinc')
,('Poor blood sugar regulation (diabetes and hypoglycaemia)','Chromium')
,('disturbed fat and protein metabolism','Chromium')
,('alcohol intolerance','Chromium')
,('impaired growth','Chromium')
,('high blood pressure','Chromium')
,('arteriosclerosis','Chromium')
,('weight loss','Chromium')
,('Fatigue','Chromium')
,('Eye problems (incl. sensitive,itching,burning,bloodshot,blurred,cataracts,opaque cornea,near sightedness,glaucoma)','Chromium')
,('irritability','Chromium')
,('frustration','Chromium')
,('Weakness','Chromium')
,('cold hands','Chromium')
,('unexplained weight loss','Chromium')
,('depression','Chromium')
,('impaired serotonin production','Chromium');